<div class="file-content code js-syntax-highlight white" id="blob-content">
    <div class="line-numbers">
        <a class="file-line-num diff-line-num"
           data-line-number="1"
           id="L1" href="#L1">1</a><a class="file-line-num diff-line-num"
           data-line-number="2"
           id="L2" href="#L2">2</a><a class="file-line-num diff-line-num"
           data-line-number="3"
           id="L3" href="#L3">3</a><a class="file-line-num diff-line-num"
           data-line-number="4"
           id="L4" href="#L4">4</a><a class="file-line-num diff-line-num"
           data-line-number="5"
           id="L5" href="#L5">5</a><a class="file-line-num diff-line-num"
           data-line-number="6"
           id="L6" href="#L6">6</a><a class="file-line-num diff-line-num"
           data-line-number="7"
           id="L7" href="#L7">7</a><a class="file-line-num diff-line-num"
           data-line-number="8"
           id="L8" href="#L8">8</a><a class="file-line-num diff-line-num"
           data-line-number="9"
           id="L9" href="#L9">9</a><a class="file-line-num diff-line-num"
           data-line-number="10"
           id="L10" href="#L10">10</a><a class="file-line-num diff-line-num"
           data-line-number="11"
           id="L11" href="#L11">11</a><a class="file-line-num diff-line-num"
           data-line-number="12"
           id="L12" href="#L12">12</a><a class="file-line-num diff-line-num"
           data-line-number="13"
           id="L13" href="#L13">13</a><a class="file-line-num diff-line-num"
           data-line-number="14"
           id="L14" href="#L14">14</a><a class="file-line-num diff-line-num"
           data-line-number="15"
           id="L15" href="#L15">15</a><a class="file-line-num diff-line-num"
           data-line-number="16"
           id="L16" href="#L16">16</a><a class="file-line-num diff-line-num"
           data-line-number="17"
           id="L17" href="#L17">17</a><a class="file-line-num diff-line-num"
           data-line-number="18"
           id="L18" href="#L18">18</a><a class="file-line-num diff-line-num"
           data-line-number="19"
           id="L19" href="#L19">19</a><a class="file-line-num diff-line-num"
           data-line-number="20"
           id="L20" href="#L20">20</a><a class="file-line-num diff-line-num"
           data-line-number="21"
           id="L21" href="#L21">21</a><a class="file-line-num diff-line-num"
           data-line-number="22"
           id="L22" href="#L22">22</a><a class="file-line-num diff-line-num"
           data-line-number="23"
           id="L23" href="#L23">23</a><a class="file-line-num diff-line-num"
           data-line-number="24"
           id="L24" href="#L24">24</a><a class="file-line-num diff-line-num"
           data-line-number="25"
           id="L25" href="#L25">25</a><a class="file-line-num diff-line-num"
           data-line-number="26"
           id="L26" href="#L26">26</a><a class="file-line-num diff-line-num"
           data-line-number="27"
           id="L27" href="#L27">27</a><a class="file-line-num diff-line-num"
           data-line-number="28"
           id="L28" href="#L28">28</a><a class="file-line-num diff-line-num"
           data-line-number="29"
           id="L29" href="#L29">29</a><a class="file-line-num diff-line-num"
           data-line-number="30"
           id="L30" href="#L30">30</a><a class="file-line-num diff-line-num"
           data-line-number="31"
           id="L31" href="#L31">31</a><a class="file-line-num diff-line-num"
           data-line-number="32"
           id="L32" href="#L32">32</a><a class="file-line-num diff-line-num"
           data-line-number="33"
           id="L33" href="#L33">33</a><a class="file-line-num diff-line-num"
           data-line-number="34"
           id="L34" href="#L34">34</a><a class="file-line-num diff-line-num"
           data-line-number="35"
           id="L35" href="#L35">35</a><a class="file-line-num diff-line-num"
           data-line-number="36"
           id="L36" href="#L36">36</a><a class="file-line-num diff-line-num"
           data-line-number="37"
           id="L37" href="#L37">37</a><a class="file-line-num diff-line-num"
           data-line-number="38"
           id="L38" href="#L38">38</a><a class="file-line-num diff-line-num"
           data-line-number="39"
           id="L39" href="#L39">39</a><a class="file-line-num diff-line-num"
           data-line-number="40"
           id="L40" href="#L40">40</a><a class="file-line-num diff-line-num"
           data-line-number="41"
           id="L41" href="#L41">41</a><a class="file-line-num diff-line-num"
           data-line-number="42"
           id="L42" href="#L42">42</a><a class="file-line-num diff-line-num"
           data-line-number="43"
           id="L43" href="#L43">43</a><a class="file-line-num diff-line-num"
           data-line-number="44"
           id="L44" href="#L44">44</a><a class="file-line-num diff-line-num"
           data-line-number="45"
           id="L45" href="#L45">45</a><a class="file-line-num diff-line-num"
           data-line-number="46"
           id="L46" href="#L46">46</a><a class="file-line-num diff-line-num"
           data-line-number="47"
           id="L47" href="#L47">47</a><a class="file-line-num diff-line-num"
           data-line-number="48"
           id="L48" href="#L48">48</a><a class="file-line-num diff-line-num"
           data-line-number="49"
           id="L49" href="#L49">49</a><a class="file-line-num diff-line-num"
           data-line-number="50"
           id="L50" href="#L50">50</a><a class="file-line-num diff-line-num"
           data-line-number="51"
           id="L51" href="#L51">51</a><a class="file-line-num diff-line-num"
           data-line-number="52"
           id="L52" href="#L52">52</a><a class="file-line-num diff-line-num"
           data-line-number="53"
           id="L53" href="#L53">53</a><a class="file-line-num diff-line-num"
           data-line-number="54"
           id="L54" href="#L54">54</a><a class="file-line-num diff-line-num"
           data-line-number="55"
           id="L55" href="#L55">55</a><a class="file-line-num diff-line-num"
           data-line-number="56"
           id="L56" href="#L56">56</a><a class="file-line-num diff-line-num"
           data-line-number="57"
           id="L57" href="#L57">57</a><a class="file-line-num diff-line-num"
           data-line-number="58"
           id="L58" href="#L58">58</a><a class="file-line-num diff-line-num"
           data-line-number="59"
           id="L59" href="#L59">59</a><a class="file-line-num diff-line-num"
           data-line-number="60"
           id="L60" href="#L60">60</a><a class="file-line-num diff-line-num"
           data-line-number="61"
           id="L61" href="#L61">61</a><a class="file-line-num diff-line-num"
           data-line-number="62"
           id="L62" href="#L62">62</a><a class="file-line-num diff-line-num"
           data-line-number="63"
           id="L63" href="#L63">63</a><a class="file-line-num diff-line-num"
           data-line-number="64"
           id="L64" href="#L64">64</a><a class="file-line-num diff-line-num"
           data-line-number="65"
           id="L65" href="#L65">65</a><a class="file-line-num diff-line-num"
           data-line-number="66"
           id="L66" href="#L66">66</a><a class="file-line-num diff-line-num"
           data-line-number="67"
           id="L67" href="#L67">67</a><a class="file-line-num diff-line-num"
           data-line-number="68"
           id="L68" href="#L68">68</a><a class="file-line-num diff-line-num"
           data-line-number="69"
           id="L69" href="#L69">69</a><a class="file-line-num diff-line-num"
           data-line-number="70"
           id="L70" href="#L70">70</a><a class="file-line-num diff-line-num"
           data-line-number="71"
           id="L71" href="#L71">71</a><a class="file-line-num diff-line-num"
           data-line-number="72"
           id="L72" href="#L72">72</a><a class="file-line-num diff-line-num"
           data-line-number="73"
           id="L73" href="#L73">73</a><a class="file-line-num diff-line-num"
           data-line-number="74"
           id="L74" href="#L74">74</a><a class="file-line-num diff-line-num"
           data-line-number="75"
           id="L75" href="#L75">75</a><a class="file-line-num diff-line-num"
           data-line-number="76"
           id="L76" href="#L76">76</a><a class="file-line-num diff-line-num"
           data-line-number="77"
           id="L77" href="#L77">77</a><a class="file-line-num diff-line-num"
           data-line-number="78"
           id="L78" href="#L78">78</a><a class="file-line-num diff-line-num"
           data-line-number="79"
           id="L79" href="#L79">79</a><a class="file-line-num diff-line-num"
           data-line-number="80"
           id="L80" href="#L80">80</a><a class="file-line-num diff-line-num"
           data-line-number="81"
           id="L81" href="#L81">81</a><a class="file-line-num diff-line-num"
           data-line-number="82"
           id="L82" href="#L82">82</a><a class="file-line-num diff-line-num"
           data-line-number="83"
           id="L83" href="#L83">83</a><a class="file-line-num diff-line-num"
           data-line-number="84"
           id="L84" href="#L84">84</a><a class="file-line-num diff-line-num"
           data-line-number="85"
           id="L85" href="#L85">85</a><a class="file-line-num diff-line-num"
           data-line-number="86"
           id="L86" href="#L86">86</a><a class="file-line-num diff-line-num"
           data-line-number="87"
           id="L87" href="#L87">87</a><a class="file-line-num diff-line-num"
           data-line-number="88"
           id="L88" href="#L88">88</a><a class="file-line-num diff-line-num"
           data-line-number="89"
           id="L89" href="#L89">89</a><a class="file-line-num diff-line-num"
           data-line-number="90"
           id="L90" href="#L90">90</a><a class="file-line-num diff-line-num"
           data-line-number="91"
           id="L91" href="#L91">91</a><a class="file-line-num diff-line-num"
           data-line-number="92"
           id="L92" href="#L92">92</a><a class="file-line-num diff-line-num"
           data-line-number="93"
           id="L93" href="#L93">93</a><a class="file-line-num diff-line-num"
           data-line-number="94"
           id="L94" href="#L94">94</a><a class="file-line-num diff-line-num"
           data-line-number="95"
           id="L95" href="#L95">95</a><a class="file-line-num diff-line-num"
           data-line-number="96"
           id="L96" href="#L96">96</a><a class="file-line-num diff-line-num"
           data-line-number="97"
           id="L97" href="#L97">97</a><a class="file-line-num diff-line-num"
           data-line-number="98"
           id="L98" href="#L98">98</a><a class="file-line-num diff-line-num"
           data-line-number="99"
           id="L99" href="#L99">99</a><a class="file-line-num diff-line-num"
           data-line-number="100"
           id="L100" href="#L100">100</a><a class="file-line-num diff-line-num"
           data-line-number="101"
           id="L101" href="#L101">101</a><a class="file-line-num diff-line-num"
           data-line-number="102"
           id="L102" href="#L102">102</a><a class="file-line-num diff-line-num"
           data-line-number="103"
           id="L103" href="#L103">103</a><a class="file-line-num diff-line-num"
           data-line-number="104"
           id="L104" href="#L104">104</a><a class="file-line-num diff-line-num"
           data-line-number="105"
           id="L105" href="#L105">105</a><a class="file-line-num diff-line-num"
           data-line-number="106"
           id="L106" href="#L106">106</a><a class="file-line-num diff-line-num"
           data-line-number="107"
           id="L107" href="#L107">107</a><a class="file-line-num diff-line-num"
           data-line-number="108"
           id="L108" href="#L108">108</a><a class="file-line-num diff-line-num"
           data-line-number="109"
           id="L109" href="#L109">109</a><a class="file-line-num diff-line-num"
           data-line-number="110"
           id="L110" href="#L110">110</a><a class="file-line-num diff-line-num"
           data-line-number="111"
           id="L111" href="#L111">111</a><a class="file-line-num diff-line-num"
           data-line-number="112"
           id="L112" href="#L112">112</a><a class="file-line-num diff-line-num"
           data-line-number="113"
           id="L113" href="#L113">113</a><a class="file-line-num diff-line-num"
           data-line-number="114"
           id="L114" href="#L114">114</a><a class="file-line-num diff-line-num"
           data-line-number="115"
           id="L115" href="#L115">115</a><a class="file-line-num diff-line-num"
           data-line-number="116"
           id="L116" href="#L116">116</a><a class="file-line-num diff-line-num"
           data-line-number="117"
           id="L117" href="#L117">117</a><a class="file-line-num diff-line-num"
           data-line-number="118"
           id="L118" href="#L118">118</a><a class="file-line-num diff-line-num"
           data-line-number="119"
           id="L119" href="#L119">119</a><a class="file-line-num diff-line-num"
           data-line-number="120"
           id="L120" href="#L120">120</a><a class="file-line-num diff-line-num"
           data-line-number="121"
           id="L121" href="#L121">121</a><a class="file-line-num diff-line-num"
           data-line-number="122"
           id="L122" href="#L122">122</a><a class="file-line-num diff-line-num"
           data-line-number="123"
           id="L123" href="#L123">123</a><a class="file-line-num diff-line-num"
           data-line-number="124"
           id="L124" href="#L124">124</a><a class="file-line-num diff-line-num"
           data-line-number="125"
           id="L125" href="#L125">125</a><a class="file-line-num diff-line-num"
           data-line-number="126"
           id="L126" href="#L126">126</a><a class="file-line-num diff-line-num"
           data-line-number="127"
           id="L127" href="#L127">127</a><a class="file-line-num diff-line-num"
           data-line-number="128"
           id="L128" href="#L128">128</a><a class="file-line-num diff-line-num"
           data-line-number="129"
           id="L129" href="#L129">129</a><a class="file-line-num diff-line-num"
           data-line-number="130"
           id="L130" href="#L130">130</a><a class="file-line-num diff-line-num"
           data-line-number="131"
           id="L131" href="#L131">131</a><a class="file-line-num diff-line-num"
           data-line-number="132"
           id="L132" href="#L132">132</a><a class="file-line-num diff-line-num"
           data-line-number="133"
           id="L133" href="#L133">133</a><a class="file-line-num diff-line-num"
           data-line-number="134"
           id="L134" href="#L134">134</a><a class="file-line-num diff-line-num"
           data-line-number="135"
           id="L135" href="#L135">135</a><a class="file-line-num diff-line-num"
           data-line-number="136"
           id="L136" href="#L136">136</a><a class="file-line-num diff-line-num"
           data-line-number="137"
           id="L137" href="#L137">137</a><a class="file-line-num diff-line-num"
           data-line-number="138"
           id="L138" href="#L138">138</a><a class="file-line-num diff-line-num"
           data-line-number="139"
           id="L139" href="#L139">139</a><a class="file-line-num diff-line-num"
           data-line-number="140"
           id="L140" href="#L140">140</a><a class="file-line-num diff-line-num"
           data-line-number="141"
           id="L141" href="#L141">141</a><a class="file-line-num diff-line-num"
           data-line-number="142"
           id="L142" href="#L142">142</a><a class="file-line-num diff-line-num"
           data-line-number="143"
           id="L143" href="#L143">143</a><a class="file-line-num diff-line-num"
           data-line-number="144"
           id="L144" href="#L144">144</a><a class="file-line-num diff-line-num"
           data-line-number="145"
           id="L145" href="#L145">145</a><a class="file-line-num diff-line-num"
           data-line-number="146"
           id="L146" href="#L146">146</a><a class="file-line-num diff-line-num"
           data-line-number="147"
           id="L147" href="#L147">147</a><a class="file-line-num diff-line-num"
           data-line-number="148"
           id="L148" href="#L148">148</a><a class="file-line-num diff-line-num"
           data-line-number="149"
           id="L149" href="#L149">149</a><a class="file-line-num diff-line-num"
           data-line-number="150"
           id="L150" href="#L150">150</a><a class="file-line-num diff-line-num"
           data-line-number="151"
           id="L151" href="#L151">151</a><a class="file-line-num diff-line-num"
           data-line-number="152"
           id="L152" href="#L152">152</a><a class="file-line-num diff-line-num"
           data-line-number="153"
           id="L153" href="#L153">153</a><a class="file-line-num diff-line-num"
           data-line-number="154"
           id="L154" href="#L154">154</a><a class="file-line-num diff-line-num"
           data-line-number="155"
           id="L155" href="#L155">155</a>
    </div>
    <div class="blob-content"
         data-blob-id="5afbd23d0e021a57af5234311b7287d5ca25c727"
         data-path="src/main/java/main/repo/EmployeeRepo.java"
         data-qa-selector="file_content">
<pre class="code highlight">
<code>
<span class="line" lang="java" id="LC1"><span class="cm">/*</span></span><span class="line" lang="java" id="LC2"><span class="cm"> * Licensed to the Apache Software Foundation (ASF) under one or more</span></span><span class="line" lang="java" id="LC3"><span class="cm"> * contributor license agreements.  See the NOTICE file distributed with</span></span><span class="line" lang="java" id="LC4"><span class="cm"> * this work for additional information regarding copyright ownership.</span></span><span class="line" lang="java" id="LC5"><span class="cm"> * The ASF licenses this file to You under the Apache License, Version 2.0</span></span><span class="line" lang="java" id="LC6"><span class="cm"> * (the &quot;License&quot;); you may not use this file except in compliance with</span></span><span class="line" lang="java" id="LC7"><span class="cm"> * the License.  You may obtain a copy of the License at</span></span><span class="line" lang="java" id="LC8"><span class="cm"> *</span></span><span class="line" lang="java" id="LC9"><span class="cm"> *      http://www.apache.org/licenses/LICENSE-2.0</span></span><span class="line" lang="java" id="LC10"><span class="cm"> *</span></span><span class="line" lang="java" id="LC11"><span class="cm"> * Unless required by applicable law or agreed to in writing, software</span></span><span class="line" lang="java" id="LC12"><span class="cm"> * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,</span></span><span class="line" lang="java" id="LC13"><span class="cm"> * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.</span></span><span class="line" lang="java" id="LC14"><span class="cm"> * See the License for the specific language governing permissions and</span></span><span class="line" lang="java" id="LC15"><span class="cm"> * limitations under the License.</span></span><span class="line" lang="java" id="LC16"><span class="cm"> */</span></span><span class="line" lang="java" id="LC17"></span><span class="line" lang="java" id="LC18"><span class="kn">package</span><span> </span><span>org.apache.commons.lang3.time</span><span>;</span></span><span class="line" lang="java" id="LC19"></span><span class="line" lang="java" id="LC20"><span class="kn">import</span><span> </span><span>java.time.Duration</span><span>;</span></span><span class="line" lang="java" id="LC21"><span class="kn">import</span><span> </span><span>java.time.temporal.ChronoUnit</span><span>;</span></span><span class="line" lang="java" id="LC22"><span class="kn">import</span><span> </span><span>java.util.Objects</span><span>;</span></span><span class="line" lang="java" id="LC23"><span class="kn">import</span><span> </span><span>java.util.concurrent.TimeUnit</span><span>;</span></span><span class="line" lang="java" id="LC24"></span><span class="line" lang="java" id="LC25"><span class="kn">import</span><span> </span><span>org.apache.commons.lang3.ObjectUtils</span><span>;</span></span><span class="line" lang="java" id="LC26"><span class="kn">import</span><span> </span><span>org.apache.commons.lang3.Range</span><span>;</span></span><span class="line" lang="java" id="LC27"><span class="kn">import</span><span> </span><span>org.apache.commons.lang3.function.FailableBiConsumer</span><span>;</span></span><span class="line" lang="java" id="LC28"><span class="kn">import</span><span> </span><span>org.apache.commons.lang3.math.NumberUtils</span><span>;</span></span><span class="line" lang="java" id="LC29"></span><span class="line" lang="java" id="LC30"><span class="cm">/**</span></span><span class="line" lang="java" id="LC31"><span class="cm"> * Utilities for {@link Duration}.</span></span><span class="line" lang="java" id="LC32"><span class="cm"> *</span></span><span class="line" lang="java" id="LC33"><span class="cm"> * @since 3.12.0</span></span><span class="line" lang="java" id="LC34"><span class="cm"> */</span></span><span class="line" lang="java" id="LC35"><span class="kd">public</span><span> </span><span class="kd">class</span><span> </span><span class="nc">DurationUtils</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC36"></span><span class="line" lang="java" id="LC37"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC38"><span class="cm">     * An Integer Range that accepts Longs.</span></span><span class="line" lang="java" id="LC39"><span class="cm">     */</span></span><span class="line" lang="java" id="LC40"><span>    </span><span class="kd">static</span><span> </span><span class="kd">final</span><span> </span><span>Range</span><span>&lt;</span><span>Long</span><span>&gt;</span><span> </span><span>LONG_TO_INT_RANGE</span><span> </span><span>=</span><span> </span><span>Range</span><span>.</span><span>between</span><span>(</span><span>NumberUtils</span><span>.</span><span>LONG_INT_MIN_VALUE</span><span>,</span></span><span class="line" lang="java" id="LC41"><span>            </span><span>NumberUtils</span><span>.</span><span>LONG_INT_MAX_VALUE</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC42"></span><span class="line" lang="java" id="LC43"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC44"><span class="cm">     * Accepts the function with the duration as a long milliseconds and int nanoseconds.</span></span><span class="line" lang="java" id="LC45"><span class="cm">     *</span></span><span class="line" lang="java" id="LC46"><span class="cm">     * @param &lt;T&gt; The function exception.</span></span><span class="line" lang="java" id="LC47"><span class="cm">     * @param consumer Accepting function.</span></span><span class="line" lang="java" id="LC48"><span class="cm">     * @param duration The duration to pick apart.</span></span><span class="line" lang="java" id="LC49"><span class="cm">     * @throws T See the function signature.</span></span><span class="line" lang="java" id="LC50"><span class="cm">     */</span></span><span class="line" lang="java" id="LC51"><span>    </span><span class="kd">public</span><span> </span><span class="kd">static</span><span> </span><span>&lt;</span><span>T</span><span> </span><span class="kd">extends</span><span> </span><span>Throwable</span><span>&gt;</span><span> </span><span class="kt">void</span><span> </span><span>accept</span><span>(</span><span class="kd">final</span><span> </span><span>FailableBiConsumer</span><span>&lt;</span><span>Long</span><span>,</span><span> </span><span>Integer</span><span>,</span><span> </span><span>T</span><span>&gt;</span><span> </span><span>consumer</span><span>,</span><span> </span><span class="kd">final</span><span> </span><span>Duration</span><span> </span><span>duration</span><span>)</span></span><span class="line" lang="java" id="LC52"><span>            </span><span class="kd">throws</span><span> </span><span>T</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC53"><span>        </span><span class="k">if</span><span> </span><span>(</span><span>consumer</span><span> </span><span>!=</span><span> </span><span class="kc">null</span><span> </span><span>&amp;&amp;</span><span> </span><span>duration</span><span> </span><span>!=</span><span> </span><span class="kc">null</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC54"><span>            </span><span>consumer</span><span>.</span><span>accept</span><span>(</span><span>duration</span><span>.</span><span>toMillis</span><span>(</span><span>)</span><span>,</span><span> </span><span>getNanosOfMiili</span><span>(</span><span>duration</span><span>)</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC55"><span>        </span><span>}</span></span><span class="line" lang="java" id="LC56"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC57"></span><span class="line" lang="java" id="LC58"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC59"><span class="cm">     * Gets the nanosecond part of a Duration converted to milliseconds.</span></span><span class="line" lang="java" id="LC60"><span class="cm">     * &lt;p&gt;</span></span><span class="line" lang="java" id="LC61"><span class="cm">     * Handy when calling an API that takes a long of milliseconds and an int of nanoseconds. For example,</span></span><span class="line" lang="java" id="LC62"><span class="cm">     * {@link Object#wait(long, int)} and {@link Thread#sleep(long, int)}.</span></span><span class="line" lang="java" id="LC63"><span class="cm">     * &lt;/p&gt;</span></span><span class="line" lang="java" id="LC64"><span class="cm">     * &lt;p&gt;</span></span><span class="line" lang="java" id="LC65"><span class="cm">     * Note that is this different from {@link Duration#getNano()} because a duration are seconds and nanoseconds.</span></span><span class="line" lang="java" id="LC66"><span class="cm">     * &lt;/p&gt;</span></span><span class="line" lang="java" id="LC67"><span class="cm">     *</span></span><span class="line" lang="java" id="LC68"><span class="cm">     * @param duration The duration to query.</span></span><span class="line" lang="java" id="LC69"><span class="cm">     * @return nanoseconds between 0 and 999,999.</span></span><span class="line" lang="java" id="LC70"><span class="cm">     */</span></span><span class="line" lang="java" id="LC71"><span>    </span><span class="kd">public</span><span> </span><span class="kd">static</span><span> </span><span class="kt">int</span><span> </span><span>getNanosOfMiili</span><span>(</span><span class="kd">final</span><span> </span><span>Duration</span><span> </span><span>duration</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC72"><span>        </span><span class="k">return</span><span> </span><span>duration</span><span>.</span><span>getNano</span><span>(</span><span>)</span><span> </span><span>%</span><span> </span><span>1</span><span>_000_000</span><span>;</span></span><span class="line" lang="java" id="LC73"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC74"></span><span class="line" lang="java" id="LC75"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC76"><span class="cm">     * Tests whether the given Duration is positive (&amp;gt;0).</span></span><span class="line" lang="java" id="LC77"><span class="cm">     *</span></span><span class="line" lang="java" id="LC78"><span class="cm">     * @param duration the value to test</span></span><span class="line" lang="java" id="LC79"><span class="cm">     * @return whether the given Duration is positive (&amp;gt;0).</span></span><span class="line" lang="java" id="LC80"><span class="cm">     */</span></span><span class="line" lang="java" id="LC81"><span>    </span><span class="kd">public</span><span> </span><span class="kd">static</span><span> </span><span class="kt">boolean</span><span> </span><span>isPositive</span><span>(</span><span class="kd">final</span><span> </span><span>Duration</span><span> </span><span>duration</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC82"><span>        </span><span class="k">return</span><span> </span><span>!</span><span>duration</span><span>.</span><span>isNegative</span><span>(</span><span>)</span><span> </span><span>&amp;&amp;</span><span> </span><span>!</span><span>duration</span><span>.</span><span>isZero</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC83"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC84"></span><span class="line" lang="java" id="LC85"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC86"><span class="cm">     * Converts a {@link TimeUnit} to a {@link ChronoUnit}.</span></span><span class="line" lang="java" id="LC87"><span class="cm">     *</span></span><span class="line" lang="java" id="LC88"><span class="cm">     * @param timeUnit A non-null TimeUnit.</span></span><span class="line" lang="java" id="LC89"><span class="cm">     * @return The corresponding ChronoUnit.</span></span><span class="line" lang="java" id="LC90"><span class="cm">     */</span></span><span class="line" lang="java" id="LC91"><span>    </span><span class="kd">static</span><span> </span><span>ChronoUnit</span><span> </span><span>toChronoUnit</span><span>(</span><span class="kd">final</span><span> </span><span>TimeUnit</span><span> </span><span>timeUnit</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC92"><span>        </span><span class="cm">// TODO when using Java &gt;= 9: Use TimeUnit.toChronoUnit().</span></span><span class="line" lang="java" id="LC93"><span>        </span><span>switch</span><span> </span><span>(</span><span>Objects</span><span>.</span><span>requireNonNull</span><span>(</span><span>timeUnit</span><span>)</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC94"><span>        </span><span>case</span><span> </span><span>NANOSECONDS</span><span>:</span></span><span class="line" lang="java" id="LC95"><span>            </span><span class="k">return</span><span> </span><span>ChronoUnit</span><span>.</span><span>NANOS</span><span>;</span></span><span class="line" lang="java" id="LC96"><span>        </span><span>case</span><span> </span><span>MICROSECONDS</span><span>:</span></span><span class="line" lang="java" id="LC97"><span>            </span><span class="k">return</span><span> </span><span>ChronoUnit</span><span>.</span><span>MICROS</span><span>;</span></span><span class="line" lang="java" id="LC98"><span>        </span><span>case</span><span> </span><span>MILLISECONDS</span><span>:</span></span><span class="line" lang="java" id="LC99"><span>            </span><span class="k">return</span><span> </span><span>ChronoUnit</span><span>.</span><span>MILLIS</span><span>;</span></span><span class="line" lang="java" id="LC100"><span>        </span><span>case</span><span> </span><span>SECONDS</span><span>:</span></span><span class="line" lang="java" id="LC101"><span>            </span><span class="k">return</span><span> </span><span>ChronoUnit</span><span>.</span><span>SECONDS</span><span>;</span></span><span class="line" lang="java" id="LC102"><span>        </span><span>case</span><span> </span><span>MINUTES</span><span>:</span></span><span class="line" lang="java" id="LC103"><span>            </span><span class="k">return</span><span> </span><span>ChronoUnit</span><span>.</span><span>MINUTES</span><span>;</span></span><span class="line" lang="java" id="LC104"><span>        </span><span>case</span><span> </span><span>HOURS</span><span>:</span></span><span class="line" lang="java" id="LC105"><span>            </span><span class="k">return</span><span> </span><span>ChronoUnit</span><span>.</span><span>HOURS</span><span>;</span></span><span class="line" lang="java" id="LC106"><span>        </span><span>case</span><span> </span><span>DAYS</span><span>:</span></span><span class="line" lang="java" id="LC107"><span>            </span><span class="k">return</span><span> </span><span>ChronoUnit</span><span>.</span><span>DAYS</span><span>;</span></span><span class="line" lang="java" id="LC108"><span>        </span><span>default</span><span>:</span></span><span class="line" lang="java" id="LC109"><span>            </span><span class="k">throw</span><span> </span><span class="k">new</span><span> </span><span>IllegalArgumentException</span><span>(</span><span>timeUnit</span><span>.</span><span>toString</span><span>(</span><span>)</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC110"><span>        </span><span>}</span></span><span class="line" lang="java" id="LC111"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC112"></span><span class="line" lang="java" id="LC113"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC114"><span class="cm">     * Converts an amount and TimeUnit into a Duration.</span></span><span class="line" lang="java" id="LC115"><span class="cm">     *</span></span><span class="line" lang="java" id="LC116"><span class="cm">     * @param amount   the amount of the duration, measured in terms of the unit, positive or negative</span></span><span class="line" lang="java" id="LC117"><span class="cm">     * @param timeUnit the unit that the duration is measured in, must have an exact duration, not null</span></span><span class="line" lang="java" id="LC118"><span class="cm">     * @return a Duration.</span></span><span class="line" lang="java" id="LC119"><span class="cm">     */</span></span><span class="line" lang="java" id="LC120"><span>    </span><span class="kd">public</span><span> </span><span class="kd">static</span><span> </span><span>Duration</span><span> </span><span>toDuration</span><span>(</span><span class="kd">final</span><span> </span><span class="kt">long</span><span> </span><span>amount</span><span>,</span><span> </span><span class="kd">final</span><span> </span><span>TimeUnit</span><span> </span><span>timeUnit</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC121"><span>        </span><span class="k">return</span><span> </span><span>Duration</span><span>.</span><span>of</span><span>(</span><span>amount</span><span>,</span><span> </span><span>toChronoUnit</span><span>(</span><span>timeUnit</span><span>)</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC122"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC123"></span><span class="line" lang="java" id="LC124"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC125"><span class="cm">     * Converts a Duration to milliseconds bound to an int (instead of a long).</span></span><span class="line" lang="java" id="LC126"><span class="cm">     * &lt;p&gt;</span></span><span class="line" lang="java" id="LC127"><span class="cm">     * Handy for low-level APIs that take millisecond timeouts in ints rather than longs.</span></span><span class="line" lang="java" id="LC128"><span class="cm">     * &lt;/p&gt;</span></span><span class="line" lang="java" id="LC129"><span class="cm">     * &lt;ul&gt;</span></span><span class="line" lang="java" id="LC130"><span class="cm">     * &lt;li&gt;If the duration milliseconds are greater than {@link Integer#MAX_VALUE}, then return</span></span><span class="line" lang="java" id="LC131"><span class="cm">     * {@link Integer#MAX_VALUE}.&lt;/li&gt;</span></span><span class="line" lang="java" id="LC132"><span class="cm">     * &lt;li&gt;If the duration milliseconds are lesser than {@link Integer#MIN_VALUE}, then return</span></span><span class="line" lang="java" id="LC133"><span class="cm">     * {@link Integer#MIN_VALUE}.&lt;/li&gt;</span></span><span class="line" lang="java" id="LC134"><span class="cm">     * &lt;/ul&gt;</span></span><span class="line" lang="java" id="LC135"><span class="cm">     *</span></span><span class="line" lang="java" id="LC136"><span class="cm">     * @param duration The duration to convert, not null.</span></span><span class="line" lang="java" id="LC137"><span class="cm">     * @return int milliseconds.</span></span><span class="line" lang="java" id="LC138"><span class="cm">     */</span></span><span class="line" lang="java" id="LC139"><span>    </span><span class="kd">public</span><span> </span><span class="kd">static</span><span> </span><span class="kt">int</span><span> </span><span>toMillisInt</span><span>(</span><span class="kd">final</span><span> </span><span>Duration</span><span> </span><span>duration</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC140"><span>        </span><span>Objects</span><span>.</span><span>requireNonNull</span><span>(</span><span>duration</span><span>,</span><span> </span><span class="s">&quot;duration&quot;</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC141"><span>        </span><span class="cm">// intValue() does not do a narrowing conversion here</span></span><span class="line" lang="java" id="LC142"><span>        </span><span class="k">return</span><span> </span><span>LONG_TO_INT_RANGE</span><span>.</span><span>fit</span><span>(</span><span>Long</span><span>.</span><span>valueOf</span><span>(</span><span>duration</span><span>.</span><span>toMillis</span><span>(</span><span>)</span><span>)</span><span>)</span><span>.</span><span>intValue</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC143"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC144"></span><span class="line" lang="java" id="LC145"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC146"><span class="cm">     * Returns the given non-null value or {@link Duration#ZERO} if null.</span></span><span class="line" lang="java" id="LC147"><span class="cm">     *</span></span><span class="line" lang="java" id="LC148"><span class="cm">     * @param duration The duration to test.</span></span><span class="line" lang="java" id="LC149"><span class="cm">     * @return The given duration or {@link Duration#ZERO}.</span></span><span class="line" lang="java" id="LC150"><span class="cm">     */</span></span><span class="line" lang="java" id="LC151"><span>    </span><span class="kd">public</span><span> </span><span class="kd">static</span><span> </span><span>Duration</span><span> </span><span>zeroIfNull</span><span>(</span><span class="kd">final</span><span> </span><span>Duration</span><span> </span><span>duration</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC152"><span>        </span><span class="k">return</span><span> </span><span>ObjectUtils</span><span>.</span><span>defaultIfNull</span><span>(</span><span>duration</span><span>,</span><span> </span><span>Duration</span><span>.</span><span>ZERO</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC153"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC154"></span><span class="line" lang="java" id="LC155"><span>}</span></span>
</code>
</pre>
    </div>
</div>