<div class="file-content code js-syntax-highlight white" id="blob-content">
    <div class="line-numbers">
        <a class="file-line-num diff-line-num"
           data-line-number="1"
           id="L1" href="#L1">1</a><a class="file-line-num diff-line-num"
           data-line-number="2"
           id="L2" href="#L2">2</a><a class="file-line-num diff-line-num"
           data-line-number="3"
           id="L3" href="#L3">3</a><a class="file-line-num diff-line-num"
           data-line-number="4"
           id="L4" href="#L4">4</a><a class="file-line-num diff-line-num"
           data-line-number="5"
           id="L5" href="#L5">5</a><a class="file-line-num diff-line-num"
           data-line-number="6"
           id="L6" href="#L6">6</a><a class="file-line-num diff-line-num"
           data-line-number="7"
           id="L7" href="#L7">7</a><a class="file-line-num diff-line-num"
           data-line-number="8"
           id="L8" href="#L8">8</a><a class="file-line-num diff-line-num"
           data-line-number="9"
           id="L9" href="#L9">9</a><a class="file-line-num diff-line-num"
           data-line-number="10"
           id="L10" href="#L10">10</a><a class="file-line-num diff-line-num"
           data-line-number="11"
           id="L11" href="#L11">11</a><a class="file-line-num diff-line-num"
           data-line-number="12"
           id="L12" href="#L12">12</a><a class="file-line-num diff-line-num"
           data-line-number="13"
           id="L13" href="#L13">13</a><a class="file-line-num diff-line-num"
           data-line-number="14"
           id="L14" href="#L14">14</a><a class="file-line-num diff-line-num"
           data-line-number="15"
           id="L15" href="#L15">15</a><a class="file-line-num diff-line-num"
           data-line-number="16"
           id="L16" href="#L16">16</a><a class="file-line-num diff-line-num"
           data-line-number="17"
           id="L17" href="#L17">17</a><a class="file-line-num diff-line-num"
           data-line-number="18"
           id="L18" href="#L18">18</a><a class="file-line-num diff-line-num"
           data-line-number="19"
           id="L19" href="#L19">19</a><a class="file-line-num diff-line-num"
           data-line-number="20"
           id="L20" href="#L20">20</a><a class="file-line-num diff-line-num"
           data-line-number="21"
           id="L21" href="#L21">21</a><a class="file-line-num diff-line-num"
           data-line-number="22"
           id="L22" href="#L22">22</a><a class="file-line-num diff-line-num"
           data-line-number="23"
           id="L23" href="#L23">23</a><a class="file-line-num diff-line-num"
           data-line-number="24"
           id="L24" href="#L24">24</a><a class="file-line-num diff-line-num"
           data-line-number="25"
           id="L25" href="#L25">25</a><a class="file-line-num diff-line-num"
           data-line-number="26"
           id="L26" href="#L26">26</a><a class="file-line-num diff-line-num"
           data-line-number="27"
           id="L27" href="#L27">27</a><a class="file-line-num diff-line-num"
           data-line-number="28"
           id="L28" href="#L28">28</a><a class="file-line-num diff-line-num"
           data-line-number="29"
           id="L29" href="#L29">29</a><a class="file-line-num diff-line-num"
           data-line-number="30"
           id="L30" href="#L30">30</a><a class="file-line-num diff-line-num"
           data-line-number="31"
           id="L31" href="#L31">31</a><a class="file-line-num diff-line-num"
           data-line-number="32"
           id="L32" href="#L32">32</a><a class="file-line-num diff-line-num"
           data-line-number="33"
           id="L33" href="#L33">33</a>
    </div>
    <div class="blob-content"
         data-blob-id="5afbd23d0e021a57af5234311b7287d5ca25c727"
         data-path="src/main/java/main/repo/EmployeeRepo.java"
         data-qa-selector="file_content">
<pre class="code highlight">
<code>
<span class="line" lang="java" id="LC1"><span class="cm">/*</span></span><span class="line" lang="java" id="LC2"><span class="cm"> * Licensed to the Apache Software Foundation (ASF) under one</span></span><span class="line" lang="java" id="LC3"><span class="cm"> * or more contributor license agreements.  See the NOTICE file</span></span><span class="line" lang="java" id="LC4"><span class="cm"> * distributed with this work for additional information</span></span><span class="line" lang="java" id="LC5"><span class="cm"> * regarding copyright ownership.  The ASF licenses this file</span></span><span class="line" lang="java" id="LC6"><span class="cm"> * to you under the Apache License, Version 2.0 (the</span></span><span class="line" lang="java" id="LC7"><span class="cm"> * &quot;License&quot;); you may not use this file except in compliance</span></span><span class="line" lang="java" id="LC8"><span class="cm"> * with the License.  You may obtain a copy of the License at</span></span><span class="line" lang="java" id="LC9"><span class="cm"> *</span></span><span class="line" lang="java" id="LC10"><span class="cm"> *   http://www.apache.org/licenses/LICENSE-2.0</span></span><span class="line" lang="java" id="LC11"><span class="cm"> *</span></span><span class="line" lang="java" id="LC12"><span class="cm"> * Unless required by applicable law or agreed to in writing,</span></span><span class="line" lang="java" id="LC13"><span class="cm"> * software distributed under the License is distributed on an</span></span><span class="line" lang="java" id="LC14"><span class="cm"> * &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY</span></span><span class="line" lang="java" id="LC15"><span class="cm"> * KIND, either express or implied.  See the License for the</span></span><span class="line" lang="java" id="LC16"><span class="cm"> * specific language governing permissions and limitations</span></span><span class="line" lang="java" id="LC17"><span class="cm"> * under the License.</span></span><span class="line" lang="java" id="LC18"><span class="cm"> */</span></span><span class="line" lang="java" id="LC19"><span class="kn">package</span><span> </span><span>org.apache.commons.io.serialization</span><span>;</span></span><span class="line" lang="java" id="LC20"></span><span class="line" lang="java" id="LC21"><span class="cm">/**</span></span><span class="line" lang="java" id="LC22"><span class="cm"> * An object that matches a Class name to a condition.</span></span><span class="line" lang="java" id="LC23"><span class="cm"> */</span></span><span class="line" lang="java" id="LC24"><span class="kd">public</span><span> </span><span class="kd">interface</span><span> </span><span class="nc">ClassNameMatcher</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC25"></span><span class="line" lang="java" id="LC26"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC27"><span class="cm">     * Returns {@code true} if the supplied class name matches this object&#39;s condition.</span></span><span class="line" lang="java" id="LC28"><span class="cm">     *</span></span><span class="line" lang="java" id="LC29"><span class="cm">     * @param className fully qualified class name</span></span><span class="line" lang="java" id="LC30"><span class="cm">     * @return {@code true} if the class name matches this object&#39;s condition</span></span><span class="line" lang="java" id="LC31"><span class="cm">     */</span></span><span class="line" lang="java" id="LC32"><span>    </span><span class="kt">boolean</span><span> </span><span>matches</span><span>(</span><span>String</span><span> </span><span>className</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC33"><span>}</span></span>
</code>
</pre>
    </div>
</div>