<div class="file-content code js-syntax-highlight white" id="blob-content">
    <div class="line-numbers">
        <a class="file-line-num diff-line-num"
           data-line-number="1"
           id="L1" href="#L1">1</a><a class="file-line-num diff-line-num"
           data-line-number="2"
           id="L2" href="#L2">2</a><a class="file-line-num diff-line-num"
           data-line-number="3"
           id="L3" href="#L3">3</a><a class="file-line-num diff-line-num"
           data-line-number="4"
           id="L4" href="#L4">4</a><a class="file-line-num diff-line-num"
           data-line-number="5"
           id="L5" href="#L5">5</a><a class="file-line-num diff-line-num"
           data-line-number="6"
           id="L6" href="#L6">6</a><a class="file-line-num diff-line-num"
           data-line-number="7"
           id="L7" href="#L7">7</a><a class="file-line-num diff-line-num"
           data-line-number="8"
           id="L8" href="#L8">8</a><a class="file-line-num diff-line-num"
           data-line-number="9"
           id="L9" href="#L9">9</a><a class="file-line-num diff-line-num"
           data-line-number="10"
           id="L10" href="#L10">10</a><a class="file-line-num diff-line-num"
           data-line-number="11"
           id="L11" href="#L11">11</a><a class="file-line-num diff-line-num"
           data-line-number="12"
           id="L12" href="#L12">12</a><a class="file-line-num diff-line-num"
           data-line-number="13"
           id="L13" href="#L13">13</a><a class="file-line-num diff-line-num"
           data-line-number="14"
           id="L14" href="#L14">14</a><a class="file-line-num diff-line-num"
           data-line-number="15"
           id="L15" href="#L15">15</a><a class="file-line-num diff-line-num"
           data-line-number="16"
           id="L16" href="#L16">16</a><a class="file-line-num diff-line-num"
           data-line-number="17"
           id="L17" href="#L17">17</a><a class="file-line-num diff-line-num"
           data-line-number="18"
           id="L18" href="#L18">18</a><a class="file-line-num diff-line-num"
           data-line-number="19"
           id="L19" href="#L19">19</a><a class="file-line-num diff-line-num"
           data-line-number="20"
           id="L20" href="#L20">20</a><a class="file-line-num diff-line-num"
           data-line-number="21"
           id="L21" href="#L21">21</a><a class="file-line-num diff-line-num"
           data-line-number="22"
           id="L22" href="#L22">22</a><a class="file-line-num diff-line-num"
           data-line-number="23"
           id="L23" href="#L23">23</a><a class="file-line-num diff-line-num"
           data-line-number="24"
           id="L24" href="#L24">24</a><a class="file-line-num diff-line-num"
           data-line-number="25"
           id="L25" href="#L25">25</a><a class="file-line-num diff-line-num"
           data-line-number="26"
           id="L26" href="#L26">26</a><a class="file-line-num diff-line-num"
           data-line-number="27"
           id="L27" href="#L27">27</a><a class="file-line-num diff-line-num"
           data-line-number="28"
           id="L28" href="#L28">28</a><a class="file-line-num diff-line-num"
           data-line-number="29"
           id="L29" href="#L29">29</a><a class="file-line-num diff-line-num"
           data-line-number="30"
           id="L30" href="#L30">30</a><a class="file-line-num diff-line-num"
           data-line-number="31"
           id="L31" href="#L31">31</a><a class="file-line-num diff-line-num"
           data-line-number="32"
           id="L32" href="#L32">32</a><a class="file-line-num diff-line-num"
           data-line-number="33"
           id="L33" href="#L33">33</a><a class="file-line-num diff-line-num"
           data-line-number="34"
           id="L34" href="#L34">34</a><a class="file-line-num diff-line-num"
           data-line-number="35"
           id="L35" href="#L35">35</a><a class="file-line-num diff-line-num"
           data-line-number="36"
           id="L36" href="#L36">36</a><a class="file-line-num diff-line-num"
           data-line-number="37"
           id="L37" href="#L37">37</a><a class="file-line-num diff-line-num"
           data-line-number="38"
           id="L38" href="#L38">38</a><a class="file-line-num diff-line-num"
           data-line-number="39"
           id="L39" href="#L39">39</a><a class="file-line-num diff-line-num"
           data-line-number="40"
           id="L40" href="#L40">40</a><a class="file-line-num diff-line-num"
           data-line-number="41"
           id="L41" href="#L41">41</a><a class="file-line-num diff-line-num"
           data-line-number="42"
           id="L42" href="#L42">42</a><a class="file-line-num diff-line-num"
           data-line-number="43"
           id="L43" href="#L43">43</a><a class="file-line-num diff-line-num"
           data-line-number="44"
           id="L44" href="#L44">44</a><a class="file-line-num diff-line-num"
           data-line-number="45"
           id="L45" href="#L45">45</a><a class="file-line-num diff-line-num"
           data-line-number="46"
           id="L46" href="#L46">46</a><a class="file-line-num diff-line-num"
           data-line-number="47"
           id="L47" href="#L47">47</a><a class="file-line-num diff-line-num"
           data-line-number="48"
           id="L48" href="#L48">48</a><a class="file-line-num diff-line-num"
           data-line-number="49"
           id="L49" href="#L49">49</a><a class="file-line-num diff-line-num"
           data-line-number="50"
           id="L50" href="#L50">50</a><a class="file-line-num diff-line-num"
           data-line-number="51"
           id="L51" href="#L51">51</a><a class="file-line-num diff-line-num"
           data-line-number="52"
           id="L52" href="#L52">52</a><a class="file-line-num diff-line-num"
           data-line-number="53"
           id="L53" href="#L53">53</a><a class="file-line-num diff-line-num"
           data-line-number="54"
           id="L54" href="#L54">54</a><a class="file-line-num diff-line-num"
           data-line-number="55"
           id="L55" href="#L55">55</a><a class="file-line-num diff-line-num"
           data-line-number="56"
           id="L56" href="#L56">56</a><a class="file-line-num diff-line-num"
           data-line-number="57"
           id="L57" href="#L57">57</a><a class="file-line-num diff-line-num"
           data-line-number="58"
           id="L58" href="#L58">58</a><a class="file-line-num diff-line-num"
           data-line-number="59"
           id="L59" href="#L59">59</a>
    </div>
    <div class="blob-content"
         data-blob-id="5afbd23d0e021a57af5234311b7287d5ca25c727"
         data-path="src/main/java/main/repo/EmployeeRepo.java"
         data-qa-selector="file_content">
<pre class="code highlight">
<code>
<span class="line" lang="java" id="LC1"><span class="cm">/*</span></span><span class="line" lang="java" id="LC2"><span class="cm"> * Licensed to the Apache Software Foundation (ASF) under one</span></span><span class="line" lang="java" id="LC3"><span class="cm"> * or more contributor license agreements.  See the NOTICE file</span></span><span class="line" lang="java" id="LC4"><span class="cm"> * distributed with this work for additional information</span></span><span class="line" lang="java" id="LC5"><span class="cm"> * regarding copyright ownership.  The ASF licenses this file</span></span><span class="line" lang="java" id="LC6"><span class="cm"> * to you under the Apache License, Version 2.0 (the</span></span><span class="line" lang="java" id="LC7"><span class="cm"> * &quot;License&quot;); you may not use this file except in compliance</span></span><span class="line" lang="java" id="LC8"><span class="cm"> * with the License.  You may obtain a copy of the License at</span></span><span class="line" lang="java" id="LC9"><span class="cm"> *</span></span><span class="line" lang="java" id="LC10"><span class="cm"> *   http://www.apache.org/licenses/LICENSE-2.0</span></span><span class="line" lang="java" id="LC11"><span class="cm"> *</span></span><span class="line" lang="java" id="LC12"><span class="cm"> * Unless required by applicable law or agreed to in writing,</span></span><span class="line" lang="java" id="LC13"><span class="cm"> * software distributed under the License is distributed on an</span></span><span class="line" lang="java" id="LC14"><span class="cm"> * &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY</span></span><span class="line" lang="java" id="LC15"><span class="cm"> * KIND, either express or implied.  See the License for the</span></span><span class="line" lang="java" id="LC16"><span class="cm"> * specific language governing permissions and limitations</span></span><span class="line" lang="java" id="LC17"><span class="cm"> * under the License.</span></span><span class="line" lang="java" id="LC18"><span class="cm"> */</span></span><span class="line" lang="java" id="LC19"><span class="kn">package</span><span> </span><span>org.apache.commons.io.serialization</span><span>;</span></span><span class="line" lang="java" id="LC20"></span><span class="line" lang="java" id="LC21"><span class="kn">import</span><span> </span><span>java.util.regex.Pattern</span><span>;</span></span><span class="line" lang="java" id="LC22"></span><span class="line" lang="java" id="LC23"><span class="cm">/**</span></span><span class="line" lang="java" id="LC24"><span class="cm"> * A {@link ClassNameMatcher} that uses regular expressions.</span></span><span class="line" lang="java" id="LC25"><span class="cm"> * &lt;p&gt;</span></span><span class="line" lang="java" id="LC26"><span class="cm"> * This object is immutable and thread-safe.</span></span><span class="line" lang="java" id="LC27"><span class="cm"> * &lt;/p&gt;</span></span><span class="line" lang="java" id="LC28"><span class="cm"> */</span></span><span class="line" lang="java" id="LC29"><span class="kd">final</span><span> </span><span class="kd">class</span><span> </span><span class="nc">RegexpClassNameMatcher</span><span> </span><span class="kd">implements</span><span> </span><span>ClassNameMatcher</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC30"></span><span class="line" lang="java" id="LC31"><span>    </span><span class="kd">private</span><span> </span><span class="kd">final</span><span> </span><span>Pattern</span><span> </span><span>pattern</span><span>;</span><span> </span><span class="cm">// Class is thread-safe</span></span><span class="line" lang="java" id="LC32"></span><span class="line" lang="java" id="LC33"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC34"><span class="cm">     * Constructs an object based on the specified regular expression.</span></span><span class="line" lang="java" id="LC35"><span class="cm">     *</span></span><span class="line" lang="java" id="LC36"><span class="cm">     * @param regex a regular expression for evaluating acceptable class names</span></span><span class="line" lang="java" id="LC37"><span class="cm">     */</span></span><span class="line" lang="java" id="LC38"><span>    </span><span class="kd">public</span><span> </span><span>RegexpClassNameMatcher</span><span>(</span><span class="kd">final</span><span> </span><span>String</span><span> </span><span>regex</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC39"><span>        </span><span>this</span><span>(</span><span>Pattern</span><span>.</span><span>compile</span><span>(</span><span>regex</span><span>)</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC40"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC41"></span><span class="line" lang="java" id="LC42"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC43"><span class="cm">     * Constructs an object based on the specified pattern.</span></span><span class="line" lang="java" id="LC44"><span class="cm">     *</span></span><span class="line" lang="java" id="LC45"><span class="cm">     * @param pattern a pattern for evaluating acceptable class names</span></span><span class="line" lang="java" id="LC46"><span class="cm">     * @throws IllegalArgumentException if {@code pattern} is null</span></span><span class="line" lang="java" id="LC47"><span class="cm">     */</span></span><span class="line" lang="java" id="LC48"><span>    </span><span class="kd">public</span><span> </span><span>RegexpClassNameMatcher</span><span>(</span><span class="kd">final</span><span> </span><span>Pattern</span><span> </span><span>pattern</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC49"><span>        </span><span class="k">if</span><span> </span><span>(</span><span>pattern</span><span> </span><span>==</span><span> </span><span class="kc">null</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC50"><span>            </span><span class="k">throw</span><span> </span><span class="k">new</span><span> </span><span>IllegalArgumentException</span><span>(</span><span class="s">&quot;Null pattern&quot;</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC51"><span>        </span><span>}</span></span><span class="line" lang="java" id="LC52"><span>        </span><span>this</span><span>.</span><span>pattern</span><span> </span><span>=</span><span> </span><span>pattern</span><span>;</span></span><span class="line" lang="java" id="LC53"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC54"></span><span class="line" lang="java" id="LC55"><span>    </span><span>@</span><span>Override</span></span><span class="line" lang="java" id="LC56"><span>    </span><span class="kd">public</span><span> </span><span class="kt">boolean</span><span> </span><span>matches</span><span>(</span><span class="kd">final</span><span> </span><span>String</span><span> </span><span>className</span><span>)</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC57"><span>        </span><span class="k">return</span><span> </span><span>pattern</span><span>.</span><span>matcher</span><span>(</span><span>className</span><span>)</span><span>.</span><span>matches</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC58"><span>    </span><span>}</span></span><span class="line" lang="java" id="LC59"><span>}</span></span>
</code>
</pre>
    </div>
</div>