<div class="file-content code js-syntax-highlight white" id="blob-content">
    <div class="line-numbers">
        <a class="file-line-num diff-line-num"
           data-line-number="1"
           id="L1" href="#L1">1</a><a class="file-line-num diff-line-num"
           data-line-number="2"
           id="L2" href="#L2">2</a><a class="file-line-num diff-line-num"
           data-line-number="3"
           id="L3" href="#L3">3</a><a class="file-line-num diff-line-num"
           data-line-number="4"
           id="L4" href="#L4">4</a><a class="file-line-num diff-line-num"
           data-line-number="5"
           id="L5" href="#L5">5</a><a class="file-line-num diff-line-num"
           data-line-number="6"
           id="L6" href="#L6">6</a><a class="file-line-num diff-line-num"
           data-line-number="7"
           id="L7" href="#L7">7</a><a class="file-line-num diff-line-num"
           data-line-number="8"
           id="L8" href="#L8">8</a><a class="file-line-num diff-line-num"
           data-line-number="9"
           id="L9" href="#L9">9</a><a class="file-line-num diff-line-num"
           data-line-number="10"
           id="L10" href="#L10">10</a><a class="file-line-num diff-line-num"
           data-line-number="11"
           id="L11" href="#L11">11</a><a class="file-line-num diff-line-num"
           data-line-number="12"
           id="L12" href="#L12">12</a><a class="file-line-num diff-line-num"
           data-line-number="13"
           id="L13" href="#L13">13</a><a class="file-line-num diff-line-num"
           data-line-number="14"
           id="L14" href="#L14">14</a><a class="file-line-num diff-line-num"
           data-line-number="15"
           id="L15" href="#L15">15</a><a class="file-line-num diff-line-num"
           data-line-number="16"
           id="L16" href="#L16">16</a><a class="file-line-num diff-line-num"
           data-line-number="17"
           id="L17" href="#L17">17</a><a class="file-line-num diff-line-num"
           data-line-number="18"
           id="L18" href="#L18">18</a><a class="file-line-num diff-line-num"
           data-line-number="19"
           id="L19" href="#L19">19</a><a class="file-line-num diff-line-num"
           data-line-number="20"
           id="L20" href="#L20">20</a><a class="file-line-num diff-line-num"
           data-line-number="21"
           id="L21" href="#L21">21</a><a class="file-line-num diff-line-num"
           data-line-number="22"
           id="L22" href="#L22">22</a><a class="file-line-num diff-line-num"
           data-line-number="23"
           id="L23" href="#L23">23</a><a class="file-line-num diff-line-num"
           data-line-number="24"
           id="L24" href="#L24">24</a><a class="file-line-num diff-line-num"
           data-line-number="25"
           id="L25" href="#L25">25</a><a class="file-line-num diff-line-num"
           data-line-number="26"
           id="L26" href="#L26">26</a><a class="file-line-num diff-line-num"
           data-line-number="27"
           id="L27" href="#L27">27</a><a class="file-line-num diff-line-num"
           data-line-number="28"
           id="L28" href="#L28">28</a><a class="file-line-num diff-line-num"
           data-line-number="29"
           id="L29" href="#L29">29</a><a class="file-line-num diff-line-num"
           data-line-number="30"
           id="L30" href="#L30">30</a><a class="file-line-num diff-line-num"
           data-line-number="31"
           id="L31" href="#L31">31</a><a class="file-line-num diff-line-num"
           data-line-number="32"
           id="L32" href="#L32">32</a><a class="file-line-num diff-line-num"
           data-line-number="33"
           id="L33" href="#L33">33</a><a class="file-line-num diff-line-num"
           data-line-number="34"
           id="L34" href="#L34">34</a><a class="file-line-num diff-line-num"
           data-line-number="35"
           id="L35" href="#L35">35</a><a class="file-line-num diff-line-num"
           data-line-number="36"
           id="L36" href="#L36">36</a><a class="file-line-num diff-line-num"
           data-line-number="37"
           id="L37" href="#L37">37</a><a class="file-line-num diff-line-num"
           data-line-number="38"
           id="L38" href="#L38">38</a><a class="file-line-num diff-line-num"
           data-line-number="39"
           id="L39" href="#L39">39</a><a class="file-line-num diff-line-num"
           data-line-number="40"
           id="L40" href="#L40">40</a><a class="file-line-num diff-line-num"
           data-line-number="41"
           id="L41" href="#L41">41</a><a class="file-line-num diff-line-num"
           data-line-number="42"
           id="L42" href="#L42">42</a><a class="file-line-num diff-line-num"
           data-line-number="43"
           id="L43" href="#L43">43</a><a class="file-line-num diff-line-num"
           data-line-number="44"
           id="L44" href="#L44">44</a><a class="file-line-num diff-line-num"
           data-line-number="45"
           id="L45" href="#L45">45</a><a class="file-line-num diff-line-num"
           data-line-number="46"
           id="L46" href="#L46">46</a><a class="file-line-num diff-line-num"
           data-line-number="47"
           id="L47" href="#L47">47</a><a class="file-line-num diff-line-num"
           data-line-number="48"
           id="L48" href="#L48">48</a><a class="file-line-num diff-line-num"
           data-line-number="49"
           id="L49" href="#L49">49</a><a class="file-line-num diff-line-num"
           data-line-number="50"
           id="L50" href="#L50">50</a><a class="file-line-num diff-line-num"
           data-line-number="51"
           id="L51" href="#L51">51</a><a class="file-line-num diff-line-num"
           data-line-number="52"
           id="L52" href="#L52">52</a><a class="file-line-num diff-line-num"
           data-line-number="53"
           id="L53" href="#L53">53</a><a class="file-line-num diff-line-num"
           data-line-number="54"
           id="L54" href="#L54">54</a><a class="file-line-num diff-line-num"
           data-line-number="55"
           id="L55" href="#L55">55</a><a class="file-line-num diff-line-num"
           data-line-number="56"
           id="L56" href="#L56">56</a><a class="file-line-num diff-line-num"
           data-line-number="57"
           id="L57" href="#L57">57</a><a class="file-line-num diff-line-num"
           data-line-number="58"
           id="L58" href="#L58">58</a><a class="file-line-num diff-line-num"
           data-line-number="59"
           id="L59" href="#L59">59</a><a class="file-line-num diff-line-num"
           data-line-number="60"
           id="L60" href="#L60">60</a><a class="file-line-num diff-line-num"
           data-line-number="61"
           id="L61" href="#L61">61</a><a class="file-line-num diff-line-num"
           data-line-number="62"
           id="L62" href="#L62">62</a><a class="file-line-num diff-line-num"
           data-line-number="63"
           id="L63" href="#L63">63</a><a class="file-line-num diff-line-num"
           data-line-number="64"
           id="L64" href="#L64">64</a><a class="file-line-num diff-line-num"
           data-line-number="65"
           id="L65" href="#L65">65</a><a class="file-line-num diff-line-num"
           data-line-number="66"
           id="L66" href="#L66">66</a><a class="file-line-num diff-line-num"
           data-line-number="67"
           id="L67" href="#L67">67</a><a class="file-line-num diff-line-num"
           data-line-number="68"
           id="L68" href="#L68">68</a><a class="file-line-num diff-line-num"
           data-line-number="69"
           id="L69" href="#L69">69</a><a class="file-line-num diff-line-num"
           data-line-number="70"
           id="L70" href="#L70">70</a><a class="file-line-num diff-line-num"
           data-line-number="71"
           id="L71" href="#L71">71</a><a class="file-line-num diff-line-num"
           data-line-number="72"
           id="L72" href="#L72">72</a><a class="file-line-num diff-line-num"
           data-line-number="73"
           id="L73" href="#L73">73</a><a class="file-line-num diff-line-num"
           data-line-number="74"
           id="L74" href="#L74">74</a><a class="file-line-num diff-line-num"
           data-line-number="75"
           id="L75" href="#L75">75</a><a class="file-line-num diff-line-num"
           data-line-number="76"
           id="L76" href="#L76">76</a><a class="file-line-num diff-line-num"
           data-line-number="77"
           id="L77" href="#L77">77</a><a class="file-line-num diff-line-num"
           data-line-number="78"
           id="L78" href="#L78">78</a><a class="file-line-num diff-line-num"
           data-line-number="79"
           id="L79" href="#L79">79</a><a class="file-line-num diff-line-num"
           data-line-number="80"
           id="L80" href="#L80">80</a><a class="file-line-num diff-line-num"
           data-line-number="81"
           id="L81" href="#L81">81</a><a class="file-line-num diff-line-num"
           data-line-number="82"
           id="L82" href="#L82">82</a><a class="file-line-num diff-line-num"
           data-line-number="83"
           id="L83" href="#L83">83</a><a class="file-line-num diff-line-num"
           data-line-number="84"
           id="L84" href="#L84">84</a><a class="file-line-num diff-line-num"
           data-line-number="85"
           id="L85" href="#L85">85</a><a class="file-line-num diff-line-num"
           data-line-number="86"
           id="L86" href="#L86">86</a><a class="file-line-num diff-line-num"
           data-line-number="87"
           id="L87" href="#L87">87</a><a class="file-line-num diff-line-num"
           data-line-number="88"
           id="L88" href="#L88">88</a><a class="file-line-num diff-line-num"
           data-line-number="89"
           id="L89" href="#L89">89</a><a class="file-line-num diff-line-num"
           data-line-number="90"
           id="L90" href="#L90">90</a><a class="file-line-num diff-line-num"
           data-line-number="91"
           id="L91" href="#L91">91</a><a class="file-line-num diff-line-num"
           data-line-number="92"
           id="L92" href="#L92">92</a><a class="file-line-num diff-line-num"
           data-line-number="93"
           id="L93" href="#L93">93</a><a class="file-line-num diff-line-num"
           data-line-number="94"
           id="L94" href="#L94">94</a>
    </div>
    <div class="blob-content"
         data-blob-id="5afbd23d0e021a57af5234311b7287d5ca25c727"
         data-path="src/main/java/main/repo/EmployeeRepo.java"
         data-qa-selector="file_content">
<pre class="code highlight">
<code>
<span class="line" lang="java" id="LC1"><span class="cm">/*</span></span><span class="line" lang="java" id="LC2"><span class="cm"> * Licensed to the Apache Software Foundation (ASF) under one or more</span></span><span class="line" lang="java" id="LC3"><span class="cm"> * contributor license agreements.  See the NOTICE file distributed with</span></span><span class="line" lang="java" id="LC4"><span class="cm"> * this work for additional information regarding copyright ownership.</span></span><span class="line" lang="java" id="LC5"><span class="cm"> * The ASF licenses this file to You under the Apache License, Version 2.0</span></span><span class="line" lang="java" id="LC6"><span class="cm"> * (the &quot;License&quot;); you may not use this file except in compliance with</span></span><span class="line" lang="java" id="LC7"><span class="cm"> * the License.  You may obtain a copy of the License at</span></span><span class="line" lang="java" id="LC8"><span class="cm"> *</span></span><span class="line" lang="java" id="LC9"><span class="cm"> *      http://www.apache.org/licenses/LICENSE-2.0</span></span><span class="line" lang="java" id="LC10"><span class="cm"> *</span></span><span class="line" lang="java" id="LC11"><span class="cm"> * Unless required by applicable law or agreed to in writing, software</span></span><span class="line" lang="java" id="LC12"><span class="cm"> * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,</span></span><span class="line" lang="java" id="LC13"><span class="cm"> * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.</span></span><span class="line" lang="java" id="LC14"><span class="cm"> * See the License for the specific language governing permissions and</span></span><span class="line" lang="java" id="LC15"><span class="cm"> * limitations under the License.</span></span><span class="line" lang="java" id="LC16"><span class="cm"> */</span></span><span class="line" lang="java" id="LC17"><span class="kn">package</span><span> </span><span>org.apache.commons.lang3.concurrent</span><span>;</span></span><span class="line" lang="java" id="LC18"></span><span class="line" lang="java" id="LC19"><span class="cm">/**</span></span><span class="line" lang="java" id="LC20"><span class="cm"> * &lt;p&gt;</span></span><span class="line" lang="java" id="LC21"><span class="cm"> * An interface describing a &lt;a</span></span><span class="line" lang="java" id="LC22"><span class="cm"> * href=&quot;http://martinfowler.com/bliki/CircuitBreaker.html&quot;&gt;Circuit Breaker&lt;/a&gt; component.</span></span><span class="line" lang="java" id="LC23"><span class="cm"> * &lt;/p&gt;</span></span><span class="line" lang="java" id="LC24"><span class="cm"> * &lt;p&gt;</span></span><span class="line" lang="java" id="LC25"><span class="cm"> * A &lt;em&gt;circuit breaker&lt;/em&gt; can be used to protect an application against unreliable</span></span><span class="line" lang="java" id="LC26"><span class="cm"> * services or unexpected load. It typically monitors a specific resource. As long as this</span></span><span class="line" lang="java" id="LC27"><span class="cm"> * resource works as expected, it stays in state &lt;em&gt;closed&lt;/em&gt;, meaning that the</span></span><span class="line" lang="java" id="LC28"><span class="cm"> * resource can be used. If problems are encountered when using the resource, the circuit</span></span><span class="line" lang="java" id="LC29"><span class="cm"> * breaker can switch into state &lt;em&gt;open&lt;/em&gt;; then access to this resource is</span></span><span class="line" lang="java" id="LC30"><span class="cm"> * prohibited. Depending on a concrete implementation, it is possible that the circuit</span></span><span class="line" lang="java" id="LC31"><span class="cm"> * breaker switches back to state &lt;em&gt;closed&lt;/em&gt; when the resource becomes available</span></span><span class="line" lang="java" id="LC32"><span class="cm"> * again.</span></span><span class="line" lang="java" id="LC33"><span class="cm"> * &lt;/p&gt;</span></span><span class="line" lang="java" id="LC34"><span class="cm"> * &lt;p&gt;</span></span><span class="line" lang="java" id="LC35"><span class="cm"> * This interface defines a generic protocol of a circuit breaker component. It should be</span></span><span class="line" lang="java" id="LC36"><span class="cm"> * sufficiently generic to be applied to multiple different use cases.</span></span><span class="line" lang="java" id="LC37"><span class="cm"> * &lt;/p&gt;</span></span><span class="line" lang="java" id="LC38"><span class="cm"> *</span></span><span class="line" lang="java" id="LC39"><span class="cm"> * @param &lt;T&gt; the type of the value monitored by this circuit breaker</span></span><span class="line" lang="java" id="LC40"><span class="cm"> * @since 3.5</span></span><span class="line" lang="java" id="LC41"><span class="cm"> */</span></span><span class="line" lang="java" id="LC42"><span class="kd">public</span><span> </span><span class="kd">interface</span><span> </span><span class="nc">CircuitBreaker</span><span>&lt;</span><span>T</span><span>&gt;</span><span> </span><span>{</span></span><span class="line" lang="java" id="LC43"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC44"><span class="cm">     * Returns the current open state of this circuit breaker. A return value of</span></span><span class="line" lang="java" id="LC45"><span class="cm">     * &lt;strong&gt;true&lt;/strong&gt; means that the circuit breaker is currently open indicating a</span></span><span class="line" lang="java" id="LC46"><span class="cm">     * problem in the monitored sub system.</span></span><span class="line" lang="java" id="LC47"><span class="cm">     *</span></span><span class="line" lang="java" id="LC48"><span class="cm">     * @return the current open state of this circuit breaker</span></span><span class="line" lang="java" id="LC49"><span class="cm">     */</span></span><span class="line" lang="java" id="LC50"><span>    </span><span class="kt">boolean</span><span> </span><span>isOpen</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC51"></span><span class="line" lang="java" id="LC52"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC53"><span class="cm">     * Returns the current closed state of this circuit breaker. A return value of</span></span><span class="line" lang="java" id="LC54"><span class="cm">     * &lt;strong&gt;true&lt;/strong&gt; means that the circuit breaker is currently closed. This</span></span><span class="line" lang="java" id="LC55"><span class="cm">     * means that everything is okay with the monitored sub system.</span></span><span class="line" lang="java" id="LC56"><span class="cm">     *</span></span><span class="line" lang="java" id="LC57"><span class="cm">     * @return the current closed state of this circuit breaker</span></span><span class="line" lang="java" id="LC58"><span class="cm">     */</span></span><span class="line" lang="java" id="LC59"><span>    </span><span class="kt">boolean</span><span> </span><span>isClosed</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC60"></span><span class="line" lang="java" id="LC61"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC62"><span class="cm">     * Checks the state of this circuit breaker and changes it if necessary. The return</span></span><span class="line" lang="java" id="LC63"><span class="cm">     * value indicates whether the circuit breaker is now in state {@code CLOSED}; a value</span></span><span class="line" lang="java" id="LC64"><span class="cm">     * of &lt;strong&gt;true&lt;/strong&gt; typically means that the current operation can continue.</span></span><span class="line" lang="java" id="LC65"><span class="cm">     *</span></span><span class="line" lang="java" id="LC66"><span class="cm">     * @return &lt;strong&gt;true&lt;/strong&gt; if the circuit breaker is now closed;</span></span><span class="line" lang="java" id="LC67"><span class="cm">     * &lt;strong&gt;false&lt;/strong&gt; otherwise</span></span><span class="line" lang="java" id="LC68"><span class="cm">     */</span></span><span class="line" lang="java" id="LC69"><span>    </span><span class="kt">boolean</span><span> </span><span>checkState</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC70"></span><span class="line" lang="java" id="LC71"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC72"><span class="cm">     * Closes this circuit breaker. Its state is changed to closed. If this circuit</span></span><span class="line" lang="java" id="LC73"><span class="cm">     * breaker is already closed, this method has no effect.</span></span><span class="line" lang="java" id="LC74"><span class="cm">     */</span></span><span class="line" lang="java" id="LC75"><span>    </span><span class="kt">void</span><span> </span><span>close</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC76"></span><span class="line" lang="java" id="LC77"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC78"><span class="cm">     * Opens this circuit breaker. Its state is changed to open. Depending on a concrete</span></span><span class="line" lang="java" id="LC79"><span class="cm">     * implementation, it may close itself again if the monitored sub system becomes</span></span><span class="line" lang="java" id="LC80"><span class="cm">     * available. If this circuit breaker is already open, this method has no effect.</span></span><span class="line" lang="java" id="LC81"><span class="cm">     */</span></span><span class="line" lang="java" id="LC82"><span>    </span><span class="kt">void</span><span> </span><span>open</span><span>(</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC83"></span><span class="line" lang="java" id="LC84"><span>    </span><span class="cm">/**</span></span><span class="line" lang="java" id="LC85"><span class="cm">     * Increments the monitored value and performs a check of the current state of this</span></span><span class="line" lang="java" id="LC86"><span class="cm">     * circuit breaker. This method works like {@link #checkState()}, but the monitored</span></span><span class="line" lang="java" id="LC87"><span class="cm">     * value is incremented before the state check is performed.</span></span><span class="line" lang="java" id="LC88"><span class="cm">     *</span></span><span class="line" lang="java" id="LC89"><span class="cm">     * @param increment value to increment in the monitored value of the circuit breaker</span></span><span class="line" lang="java" id="LC90"><span class="cm">     * @return &lt;strong&gt;true&lt;/strong&gt; if the circuit breaker is now closed;</span></span><span class="line" lang="java" id="LC91"><span class="cm">     * &lt;strong&gt;false&lt;/strong&gt; otherwise</span></span><span class="line" lang="java" id="LC92"><span class="cm">     */</span></span><span class="line" lang="java" id="LC93"><span>    </span><span class="kt">boolean</span><span> </span><span>incrementAndCheckState</span><span>(</span><span>T</span><span> </span><span>increment</span><span>)</span><span>;</span></span><span class="line" lang="java" id="LC94"><span>}</span></span>
</code>
</pre>
    </div>
</div>